[project]
name = "llm-chat-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.97.1",
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
]
